apiVersion: v2
name: devops-monitor
description: DevOps Monitor - A multi-tenant GitHub App for monitoring GitHub Actions workflows
type: application
version: 0.2.0
appVersion: "1.1.0"
keywords:
  - github
  - actions
  - monitoring
  - ci-cd
  - devops
maintainers:
  - name: cfir
home: https://github.com/opsyard/devops-monitor
sources:
  - https://github.com/opsyard/devops-monitor