{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-monitor.fullname" . }}-frontend
  labels:
    {{- include "devops-monitor.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devops-monitor.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
